"use client";

import { useEffect, useState } from "react";
import { FileText, LoaderCircle, Plus, RefreshCw, TriangleAlert, X } from "lucide-react";

type Status = { wabas: Array<{id:string;name:string}> };
type Template = { id:string;name:string;language:string;status:string;category:string;components:Array<{type?:string;text?:string}> };
const input="w-full rounded-lg border border-zinc-200 bg-white px-3 py-2 text-[12px] text-zinc-900 outline-none focus:border-zinc-400 dark:border-zinc-800 dark:bg-zinc-950 dark:text-zinc-100";

export default function PainelTemplates(){
  const [status,setStatus]=useState<Status|null>(null); const [lista,setLista]=useState<Template[]>([]); const [erro,setErro]=useState(""); const [ocupado,setOcupado]=useState(true); const [criando,setCriando]=useState(false);
  async function carregar(){setOcupado(true);setErro("");const r=await fetch("/api/meta/status");const s=await r.json();if(!r.ok){setErro(s.erro);setOcupado(false);return}setStatus(s);if(!s.wabas?.length){setErro(s.erroWhatsApp??"Nenhuma conta do WhatsApp Business foi atribuída ao usuário de sistema chroma-crm.");setOcupado(false);return}const tr=await fetch(`/api/meta/templates?waba=${encodeURIComponent(s.wabas[0].id)}`);const tj=await tr.json();if(tr.ok)setLista(tj.templates);else setErro(tj.erro);setOcupado(false)}
  // A busca inicial sincroniza esta client view com a API externa.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void carregar()},[]);
  return <div className="min-h-screen bg-conteudo"><div className="mx-auto w-full max-w-6xl px-6 py-8"><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-lg font-semibold tracking-tight text-zinc-900 dark:text-zinc-50">Templates</h1><p className="mt-1 text-[12px] text-zinc-500 dark:text-zinc-400">Crie mensagens oficiais e acompanhe a aprovação pela Meta.</p></div><div className="flex gap-2"><button onClick={()=>void carregar()} className="rounded-lg border border-zinc-200 p-2 text-zinc-500 dark:border-zinc-800"><RefreshCw className={`size-4 ${ocupado?"animate-spin":""}`}/></button><button disabled={!status?.wabas.length} onClick={()=>setCriando(true)} className="flex items-center gap-1.5 rounded-full bg-zinc-900 px-4 py-2 text-[12px] font-medium text-white disabled:opacity-40 dark:bg-zinc-50 dark:text-zinc-900"><Plus className="size-3.5"/>Novo template</button></div></header>
  {erro&&<div className="mt-5 flex gap-2 rounded-2xl border border-amber-300 bg-amber-50/60 p-4 text-[12px] text-amber-800 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-200"><TriangleAlert className="size-4 shrink-0"/><div>{erro}<p className="mt-1 opacity-75">Permissões concedidas; falta atribuir a WABA e o número como ativos do usuário de sistema.</p></div></div>}
  {ocupado?<Vazio texto="Consultando templates…" girando/>:!erro&&lista.length===0?<Vazio texto="Nenhum template criado nesta conta."/>:<div className="mt-6 grid gap-3 md:grid-cols-2">{lista.map(t=><article key={t.id} className="rounded-2xl border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-950"><div className="flex items-center justify-between gap-2"><h2 className="truncate text-[13px] font-semibold text-zinc-900 dark:text-zinc-50">{t.name}</h2><Estado valor={t.status}/></div><p className="mt-1 text-[10px] uppercase tracking-wide text-zinc-400">{t.category} · {t.language}</p><p className="mt-4 whitespace-pre-wrap rounded-xl bg-zinc-50 p-3 text-[12px] leading-relaxed text-zinc-600 dark:bg-zinc-900 dark:text-zinc-300">{t.components.find(c=>c.type==="BODY")?.text??"Sem corpo"}</p></article>)}</div>}
  {criando&&status?.wabas[0]&&<Form waba={status.wabas[0].id} fechar={()=>setCriando(false)} salvo={()=>{setCriando(false);void carregar()}}/>}</div></div>;
}

function Form({waba,fechar,salvo}:{waba:string;fechar:()=>void;salvo:()=>void}){const[nome,setNome]=useState("");const[corpo,setCorpo]=useState("");const[rodape,setRodape]=useState("");const[categoria,setCategoria]=useState("MARKETING");const[erro,setErro]=useState("");const[ocupado,setOcupado]=useState(false);async function enviar(){setOcupado(true);setErro("");const r=await fetch("/api/meta/templates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({waba,nome,corpo,rodape,categoria,idioma:"pt_BR"})});const j=await r.json();setOcupado(false);if(r.ok)salvo();else setErro(j.erro)}return <div className="fixed inset-0 z-50 flex justify-end bg-black/30" onMouseDown={e=>{if(e.target===e.currentTarget)fechar()}}><section className="h-full w-full max-w-lg overflow-y-auto bg-white p-6 shadow-2xl dark:bg-zinc-950"><div className="flex items-center justify-between"><div><h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-50">Novo template</h2><p className="mt-1 text-[11px] text-zinc-500">Será enviado para análise da Meta.</p></div><button onClick={fechar} className="p-2 text-zinc-400"><X className="size-4"/></button></div><div className="mt-6 space-y-4"><Campo titulo="Nome"><input className={input} value={nome} onChange={e=>setNome(e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,"_"))} placeholder="promocao_setembro"/></Campo><Campo titulo="Categoria"><select className={input} value={categoria} onChange={e=>setCategoria(e.target.value)}><option value="MARKETING">Marketing</option><option value="UTILITY">Utilidade</option></select></Campo><Campo titulo="Corpo"><textarea className={`${input} min-h-40 resize-y`} maxLength={1024} value={corpo} onChange={e=>setCorpo(e.target.value)} placeholder="Olá {{1}}, temos uma novidade para você."/><span className="mt-1 block text-right text-[10px] text-zinc-400">{corpo.length}/1024</span></Campo><Campo titulo="Rodapé · opcional"><input className={input} maxLength={60} value={rodape} onChange={e=>setRodape(e.target.value)}/></Campo>{erro&&<p className="text-[11px] text-red-600">{erro}</p>}<button disabled={ocupado||!nome||!corpo} onClick={()=>void enviar()} className="flex items-center gap-1.5 rounded-full bg-zinc-900 px-4 py-2 text-[12px] font-medium text-white disabled:opacity-40 dark:bg-zinc-50 dark:text-zinc-900">{ocupado&&<LoaderCircle className="size-3.5 animate-spin"/>}Enviar para aprovação</button></div></section></div>}
function Campo({titulo,children}:{titulo:string;children:React.ReactNode}){return <label className="block text-[11px] font-medium text-zinc-500">{titulo}<div className="mt-1">{children}</div></label>}
function Estado({valor}:{valor:string}){const ok=valor==="APPROVED";return <span className={`rounded-full px-2 py-0.5 text-[10px] font-medium ${ok?"bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300":"bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300"}`}>{valor}</span>}
function Vazio({texto,girando}:{texto:string;girando?:boolean}){return <div className="mt-8 flex flex-col items-center rounded-2xl border border-dashed border-zinc-300 py-12 dark:border-zinc-700">{girando?<LoaderCircle className="size-5 animate-spin text-zinc-400"/>:<FileText className="size-5 text-zinc-400"/>}<p className="mt-2 text-[12px] text-zinc-500">{texto}</p></div>}
